### ISSUE TITLE
Frozen on Cast Dashboard

### ISSUE THREAD

**Issue by markus99** [pmongloid/flipdown-timer-card#24]
I am using Google Cast (https://www.home-assistant.io/integrations/cast/) with Flipdown Timer Card on a dashboard.  I'm casting to a 10" Lenovo Hub.

The card does cast successfully, but the timer remains frozen and doesn't update.  

I have a 10 minute countdown timer for my kid's school bus pickup displayed as:
```
          card:
            type: custom:flipdown-timer-card
            entity: timer.school_bus
            style: |
              ha-card #states {
                margin-bottom: -5px !important;
                padding-top: 1px !important;
                padding-bottom: 9px;
              }
              .button-group {
                display: none;
              }
            show_hour: false
            show_header: false
```
The display remains at `09:59` and doesn't update.  Anything to be done to have it update on this 'cast' dashboard?

**Comment by pmongloid** [comment]
does built-in timer card(just entities card) work?

**Comment by markus99** [comment]
Just checked this.  These appear to update every ~60 seconds.  So a 10m timer will show 9:59, then 8:59, 7:59, etc. - again, only when cast.  On PC/phone each works fine.

**Comment by pmongloid** [comment]
It is behavior of setInterval function that is supposed to run a function every second, but it slows down when the screen is inactive.
seems it's regarded as background run when casted and then it's hard to fix since it's kind of the policies of  the browser.
Need to check if your timer entity works on casted screen with built in entities card.
